### ISSUE TITLE
Name this better - is this the withdrawn token amount?

### ISSUE THREAD

**Issue by Perseverance** [maptuhec/vesting#4]
https://github.com/maptuhec/vesting/blob/beed2c6fb0c8209ab464c66f310188dbe6511131/contracts/Vesting.sol#L7

If this is the withdrawn token amount name it better. If this is the total token balance you should not be storing it but instead of reading it from the vesting contract on the fly

**Comment by maptuhec** [comment]
Done, I have removed the token amount for now
