### ISSUE TITLE
Will I loose my tokens forever?

### ISSUE THREAD

**Issue by Perseverance** [maptuhec/vesting#6]
https://github.com/maptuhec/vesting/blob/608288d080b38d6f1912214c704b874b9476a599/contracts/Vesting.sol#L58

There is this part of the requirement:
'Once the owner calls claim, he will claim all unclaimed tokens from this and any previous periods.'

So lets look at your code. Two scenarios - what will happen:
1. I have 'missed' the first period (decided not to withdraw my money in the first period) - will I be able to get them at a later period?
2. I've claimed my first period tokens, but missed the second period - will I be able to get them at a later period?

**Comment by maptuhec** [comment]
Fixed
